#!/bin/bash
# Archstall Arch Linux installer made by PowerMan2206

# set style variables
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
bold=$(tput bold)
italic=$(tput sitm)
end=$(tput sgr0)

mountpoint=/mnt
packages=/tmp/packages
packagesclean=/tmp/packagesclean

#functions
error() {
	echo "${bold}${red}ERROR:$end $1"
}

invalidoption() {
	error "invalid option!"
}

namepartition() {
	lsblk -rno name | grep "$disk" | sed 1d | sed -n "$1"p
}

autocomplete() {
	cd $(mktemp -d)
	touch $@
}

clear 

echo "${bold}${green}Archstall Arch Linux installer$end"
echo "${red}This script comes with no warranty, your system is your own responsibility$end"
echo "https://github.com/PowerMan2206/archstall"
echo
echo "The script is made to help you install Arch Linux,"
echo "not make the process idiot-proof. Don't be an idiot."
echo

if ! grep -q "IMAGE_ID=archlinux" /etc/os-release; then
	echo "${red}Non-Arch Linux live environment detected!$end"
	echo "The script may still work, but an Arch Linux live environment is ${bold}strongly$end"
	echo "recommended since it has all the required packages already installed"
else
	echo "Using the latest Arch Linux live environment is recommended"
fi

echo
read -n 1 -sp "Press any key to continue... "
echo; echo

# check the boot mode
if [[ ! -f /sys/firmware/efi/fw_platform_size ]]; then
	echo "${red}System booted in ${bold}BIOS$end$red mode!$end"
	echo "The script does not support installing in BIOS mode"
	echo "boo-womp for you"
	exit
elif [[ $(cat /sys/firmware/efi/fw_platform_size) != 64 ]]; then
	echo "${red}System not booted in ${bold}64-bit UEFI$end$red mode!$end"
	echo "This causes problems within the script and- 32-bit UEFI, man? Really?"
	exit
fi

clear

# unmount anything in the mountpoint
if [[ $(findmnt "$mountpoint") ]]; then
	echo "Unmounting disks in $mountpoint..."
	umount -R "$mountpoint" || exit
	echo
fi

# for read tab autocomplete
cd /dev

# choose disk
lsblk -dno name,size
echo
while true; do
	read -ep "Select the ${yellow}disk$end you want to use: /dev/" disk
	if [[ "$(lsblk -dno name)" != *"$disk"* ]] || [[ "$disk" == "" ]]; then 
		error "disk doesn't exist!"
		echo
	elif [[ "$(lsblk -dno name)" == *"$disk"* ]]; then break
	fi
done

# partition disk
while true; do
	autocomplete automatic manual skip
	read -ep "(a)utomatic, (m)anual, or (s)kip disk partitioning? [automatic] " partitioning
	echo
	
	case $partitioning in
		a | automatic | "" )
			echo "The disk will be partitioned into a 512M ${bold}EFI partition$end and a ${bold}root partition$end that takes up the rest"
			echo
			echo "${bold}${red}WARNING: THIS WILL ERASE EVERYTHING ON THE SELECTED DISK$end"
			read -sp "${red}Are you SURE you want to continue?$end You can cancel with Ctrl+C"
			echo
			echo -n "${red}Erasing disk in "
			
			# shit works
			for delet in {5..1}; do
				echo -n $delet
				for dot in {1..3}; do
					sleep 0.25
					echo -n .
				done
				sleep 0.5
				echo -n " "
			done
			echo "$end"
			
			echo
			parted -s /dev/"$disk" mklabel gpt || exit
			
			# make EFI partition
			echo "${green}Making the ${bold}EFI partition...$end"
			parted -s /dev/"$disk" mkpart P1 1MiB 512MiB || exit
			efipartition="$(namepartition 1)"
			
			# format EFI partition
			echo "${green}Formatting the EFI partition...$end"
			mkfs.fat -F32 /dev/"$efipartition"
			echo
			
			# make root partition
			echo "${green}Making the ${bold}root partition...$end"
			parted -s /dev/"$disk" mkpart P2 512MiB 100% || exit
			rootpartition="$(namepartition 2)"
	
			break
			;;
		
		m | manual | s | skip )
			case $partitioning in
				m | manual )
					autocomplete fdisk cfdisk parted
					
					while true; do
					read -ep "Do you want to use (f)disk, (c)fdisk or (p)arted? [fdisk] " partitioner
					echo
					
					case "$partitioner" in
						f | fdisk | "" ) fdisk /dev/"$disk" || exit; break ;;
						c | cfdisk ) cfdisk /dev/"$disk" || exit; break ;;
						p | parted ) parted /dev/"$disk" || exit; break ;;
						* ) invalidoption ;;	
					esac
					done # while loop
					
					clear
					;;
				s | skip ) echo "Skipping..." ;;
			esac
			
			echo
			
			# this again
			cd /dev
			
			partitions="$(lsblk -rno name,size | grep $disk | sed 1d)"
			echo "$partitions"
			echo
			
			while true; do
				read -ep "What's the ${bold}root partition${end}? /dev/" rootpartition
				if [[ "$partitions" != *"$rootpartition"* ]] || [[ "$rootpartition" == "" ]] || [[ "$rootpartition" == "$disk" ]]; then
					error "partition doesn't exist!"
					echo
				else break
				fi
			done # while loop
			
			echo
			efipartitions="$(lsblk -rno name,size | grep $disk | sed 1d | grep -v "$rootpartition")"
			echo "$efipartitions"
			echo
			
			while true; do
				read -ep "What's the ${bold}EFI partition${end}? /dev/" efipartition
				if [[ "$efipartitions" != *"$efipartition"* ]] || [[ "$efipartition" == "" ]] || [[ "$efipartition" == "$disk" ]]; then
					error "partition doesn't exist!"
					echo
				else
					while true; do
						echo
						echo "Do you want to format the ${bold}EFI partition?$end"
						read -p "${red}Don't do this if you set it up beforehand$end [n] " formatefi
						
						case $formatefi in
							n | no | "" ) echo "${green}Skipping EFI partition formatting...$end"; break ;;
							y | yes )
								echo "${green}Formatting the EFI partition...$end"
								mkfs.fat -F32 "$efipartition" || exit
								break
								;;
						esac
					done # while loop		# this
					break					# is
				fi							# a
			done # while loop				# beautiful
			break							# mess
			;;
	esac
done

echo

clear

echo "${green}Formatting the ${bold}root partition$end ${green}...$end"
echo
case $partitioning in
	m | manual | s | skip )
		echo "${red}${bold}WARNING: THIS WILL ERASE EVERYTHING ON THE ROOT PARTITION$end (duh)"
		read -p "Press enter to continue..."
		;;
esac
mkfs.ext4 -F /dev/"$rootpartition" || exit

echo

# mount partition
echo "${green}Mounting the partitions...$end"
mount /dev/"$rootpartition" "$mountpoint" || exit
mkdir "$mountpoint"/efi || exit
mount /dev/"$efipartition" "$mountpoint"/efi || exit

clear

echo "Updating the keyring..."
# yeahyeah -Sy bad
pacman --noconfirm -Sy archlinux-keyring || exit

echo

# create the package list
echo "${green}Writing the package list...$end"
cat << 'EOF' >> $packages
linux
#linux-lts
linux-firmware
polkit

nano
#micro
#vim

neofetch
#man-db
#pipewire
EOF

echo

while true; do
	# edit package list
	echo "Add/uncomment packages which you want to install in the package list"
	echo "${yellow}Linux, the firmware, polkit, nano, and neofetch are installed by default$end"
	echo "(also base and base-devel but you can't remove those because the installer breaks)"
	echo
	
	while true; do
		autocomplete nano vim skip
		read -ep "Do you want to edit the package list with (n)ano, (v)im, or (s)kip? [nano] " editor
		echo
		
		case "$editor" in
			n | nano | "" ) nano $packages; break ;;
			v | vim ) vim $packages; break ;;
			s | skip ) echo "${green}Skipping package list editing...$end"; break ;;
			* ) invalidoption ;;
		esac
	done # while loop
	
	echo
	
	# take the packages list and get rid of the comments
	echo "Cleaning the package list of comments..."
	grep -v "#" $packages > $packagesclean || exit
	
	echo
	
	# ask if user wants to enable parallel downloads for pacman/pacstrap
	while true; do
		read -ep "Enable ${yellow}parallel downloads$end for pacman? [y] " paralleldownloads
		case "$paralleldownloads" in
			y | yes | "" )
				sed -i 's/#ParallelDownloads/ParallelDownloads/g' /etc/pacman.conf
				break
				;;
			n | no )
				echo "Skipping..."
				break
				;;
		esac
	done # while loop

	clear

	# read the package list and install those packages
	echo "${green}Installing packages with pacstrap...$end"
	echo
	# using -P in case parallel downloads are used
	if ! pacstrap -P "$mountpoint" base base-devel - < $packagesclean; then
		echo
		echo "${red}Something went wrong!$end"
		echo "Read pacstrap message above"
		echo "Perhaps a space at the end of a package name?"
		read -n 1 -sp "Press any key to retry... "
		clear
	else break
	fi
done # while loop

declare -p disk rootpartition > "$mountpoint"/varstuff 2> /dev/null

echo

# make the fstab
echo "${green}Generating the fstab...$end"
genfstab -U "$mountpoint" > "$mountpoint"/etc/fstab || exit

clear

# write the second script
echo "${green}Writing the second script...$end"
echo

#----------------------------------------------------------------------------------------------------------------------
#======================================================================================================================
# START OF SCRIPT 2
cat << 'EOF' > "$mountpoint"/archstall2
#!/bin/bash

# set style variables
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
bold=$(tput bold)
end=$(tput sgr0)

# source the variables from the previous script
source /varstuff

# functions
error() {
	echo "${bold}${red}ERROR:$end $1"
}

invalidoption() {
	error "invalid option!"
}

autocomplete() {
	cd $(mktemp -d)
	touch $@
}

# select timezone stuff
cd /usr/share/zoneinfo; ls
echo

while true; do
	read -ep "Select your ${yellow}region$end: " timezone

	if [[ "$timezone" == "" ]] || [[ -d "$timezone" ]]; then invalidoption
	elif [[ -f /usr/share/zoneinfo/"$timezone" ]]; then
		echo
		echo "${green}Setting the ${bold}timezone$end${green}...$end"
		ln -sf /usr/share/zoneinfo/"$timezone" /etc/localtime
		break
	else invalidoption
	fi
done # while loop

echo

# somethingsomething time
echo "${green}Generating ${bold}/etc/adjtime$end${green}...$end"
hwclock --systohc || exit

echo

# locale stuff (???)
echo "${green}Setting the ${bold}locale$end${green}...$end"
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen || exit
echo "LANG=en_US.UTF-8" > /etc/locale.conf

clear

read -p "${yellow}hostname$end [localhost] : " hostname
echo "${green}Setting the$end ${yellow}hostname$end${green}...$end"
case "$hostname" in
	"" ) echo localhost > /etc/hostname ;;
	* ) echo "$hostname" > /etc/hostname ;;
esac

echo

# for some reason I really like this piece of code
# it's just so short and great, works perfectly
# I just think it's neat
echo "${red}Setting the root password...$end"
while true; do
	if ! passwd; then echo
	else break
	fi
done

echo

read -rp "${yellow}username$end: (empty for no user) " username
username="${username,,}"
case "$username" in
	"" ) echo "Skipping..." ;;
	* ) 
		echo "${green}Adding user$end ${yellow}$username$end"
		useradd -m "$username" || exit
		
		echo "${green}Setting the$end ${yellow}user$end ${green}password...$end"
		while true; do
			if ! passwd "$username"; then echo
			else break
			fi
		done
		
		# sudo stuff
		gpasswd -a "$username" wheel
		sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers
		
		while true; do
			# AUR helper
			read -p "Install ${yellow}paru$end? [n] " aur
			echo
			case "$aur" in
				y | yes )
					pacman -S git --noconfirm
					cd /home/"$username"
					sudo -u "$username" git clone https://aur.archlinux.org/paru-bin.git
					cd paru-bin
					sudo -u "$username" makepkg -si --noconfirm
					cd ..
					rm -rf paru-bin
					break
					;;
				
				n | no | "" ) echo "Skipping..."; break ;;
			esac
		done
		;;
esac

echo

while true; do
	# network setup
	autocomplete systemd-networkd networkmanager skip
	read -ep "Configure ${yellow}systemd-network(d)$end, ${yellow}(n)etworkmanager$end, or (s)kip? [systemd-networkd] " network
	echo
	
	case "$network" in
		d | systemd-networkd | "" )
			# takes the long `ip a` output and shortens it down to just the interfaces
			interfaces="$(ip -brief address | cut -d' ' -f1 | grep -v lo)"
			echo "$interfaces"
			echo
			
			# hacky way to get autocomplete because interfaces aren't files somehow
			cd "$(mktemp -d)"
			for inter in "$interfaces"; do touch "$inter"; done
			
			while true; do
				read -ep "Select your ${yellow}interface$end: " interface
				if [[ "$interfaces" != *"$interface"* ]] || [[ "$interface" == "" ]]; then
					error "interface doesn't exist!"
					echo
				else break
				fi
			done # while loop
			
			echo
	
			# cat thing doesn't work for some reason
			echo "${green}Writing configuration file...$end"
			echo -e "[Match]\\nName=$interface\\n[Network]\\nDHCP=yes" >> /etc/systemd/network/wired-network.network
			
			echo "${green}Enabling services...$end"
			systemctl enable systemd-networkd systemd-resolved || exit
			
			break
			;;
		
		n | networkmanager )
			echo "${green}Installing NetworkManager...$end"
			pacman -S networkmanager --noconfirm || exit
			echo
			echo "${green}Enabling service...$end"
			systemctl enable NetworkManager || exit
			
			break
			;;
		
		s | skip ) echo "Skipping..."; break ;;
		* ) invalidoption ;;
	esac
done # while loop

echo

while true; do
	read -p "Use a ${blue}Swapfile$end? [n] " swap
	echo
	
	case "$swap" in
		y | yes )
			while true; do
			read -p "Swapfile size (in MB) [2000]: " swapsize
			if [[ "$swapsize" == "" ]]; then swapsize=2000; fi
			case "$swapsize" in
				*[!0-9]* )
					echo "Value not a number!"
					echo 
					;;
				* )
					echo "${green}Making Swap...$end"
					mkswap -U clear --size "$swapsize"M --file /swapfile || exit
					swapon /swapfile
					echo "/swapfile none swap defaults 0 0" >> /etc/fstab
					
					break
					;;
			esac
			
			done # while loop
			break
			;;	
		
		n | no | "" ) echo "Skipping..."; break ;;
		* ) invalidoption ;;
	esac
done # while loop

echo

# microcode stuff
echo "${green}Installing the CPU microcode...$end"
while true; do
	autocomplete amd intel
	read -ep "${blue}Intel$end or ${red}AMD$end CPU? " cpu
	echo
	case "$cpu" in
		a | amd ) pacman -S amd-ucode --noconfirm || exit; break ;;
		i | intel ) pacman -S intel-ucode --noconfirm || exit; break ;;
		skip ) echo "Skipping..."; break ;; # secret option
		* )	invalidoption ;;
	esac
done

echo

# bootloader
echo "${green}Installing rEFInd...$end"
echo
pacman -S refind --noconfirm || exit
refind-install

# refind config stuff because it does it wrong
echo "\"Boot using default options\"     \"root=/dev/$rootpartition rw\"" > /boot/refind_linux.conf

echo

EOF
# END OF SCRIPT 2
#======================================================================================================================
#----------------------------------------------------------------------------------------------------------------------

chmod +x "$mountpoint"/archstall2

# chroot in and run the second script
echo "${green}Chrooting...$end"
echo
arch-chroot "$mountpoint" /archstall2 || exit

clear

# cleanup
echo "${green}Cleaning up files...$end"
rm "$mountpoint"/archstall2 "$mountpoint"/varstuff $packages $packagesclean

echo

# wait a bit because yes
sleep 1

# unmount the filesystems
echo "${green}Unmounting filesystems...$end"
umount -R "$mountpoint"

echo

# end
echo "${bold}${green}Installation finished!$end"
read -n 1 -sp "Press any key to reboot... "
echo

reboot
